//Z-отчет
export const GET_REPORT_Z_STARTED = 'GET_REPORT_Z_STARTED';
export const GET_REPORT_Z_SUCCESS = 'GET_REPORT_Z_SUCCESS';
export const GET_REPORT_Z_FAILURE = 'GET_REPORT_Z_FAILURE';
//X-отчет
export const GET_REPORT_X_STARTED = 'GET_REPORT_X_STARTED';
export const GET_REPORT_X_SUCCESS = 'GET_REPORT_X_SUCCESS';
export const GET_REPORT_X_FAILURE = 'GET_REPORT_X_FAILURE';
//Смена-отчет
export const GET_REPORT_SMENA_STARTED = 'GET_REPORT_SMENA_STARTED';
export const GET_REPORT_SMENA_SUCCESS = 'GET_REPORT_SMENA_SUCCESS';
export const GET_REPORT_SMENA_FAILURE = 'GET_REPORT_SMENA_FAILURE';
//Номер смены
export const GET_NUMBER_SMENA_STARTED = 'GET_NUMBER_SMENA_STARTED';
export const GET_NUMBER_SMENA_SUCCESS = 'GET_NUMBER_SMENA_SUCCESS';
export const GET_NUMBER_SMENA_FAILURE = 'GET_NUMBER_SMENA_FAILURE';
//Открыть смену
export const OPEN_SMENA_SUCCESS = 'OPEN_SMENA_SUCCESS';
export const OPEN_SMENA_FAILURE = 'OPEN_SMENA_FAILURE';
//Закрыть смену
export const CLOSE_SMENA_SUCCESS = 'CLOSE_SMENA_SUCCESS';
export const CLOSE_SMENA_FAILURE = 'CLOSE_SMENA_FAILURE';
//Для отчистки всех отчетов
export const CLEAR_ALL_REPORTS = 'CLEAR_ALL_REPORTS';