export const FINDCHECK_RESET = 'FINDCHECK_RESET';
export const FINDCHECK_STARTED = 'FINDCHECK_STARTED';
export const FINDCHECK_STOPPED = 'FINDCHECK_STOPPED';
export const FINDCHECK_FAILED  = 'FINDCHECK_FAILED';

export const FINDCHECK_START_WAIT = 'FINDCHECK_START_WAIT';
export const FINDCHECK_WAIT_ERROR = 'FINDCHECK_WAIT_ERROR';
export const FINDCHECK_SCANNED    = 'FINDCHECK_SCANNED';

export const FINDCHECK_START_SEARCH = 'FINDCHECK_START_SEARCH';
export const FINDCHECK_SEARCH_ERROR = 'FINDCHECK_SEARCH_ERROR';
export const FINDCHECK_FOUND        = 'FINDCHECK_FOUND';
