export const GET_MESSAGESNOW = 'GET_MESSAGESNOW';
export const ANSWER_MASSIVE = 'ANSWER_MASSIVE';
export const LENGTH_MASSIVE = 'LENGTH_MASSIVE';
export const GET_ANSWER_TEXT_MESSAGES = 'GET_ANSWER_TEXT_MESSAGES';
export const ANSWER_MESSAGES = 'ANSWER_MESSAGES';
